
import static Conexion.Conexion.*;
import java.awt.HeadlessException;
import java.awt.image.BufferedImage;
import java.io.ByteArrayInputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JComponent;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import static javax.swing.JOptionPane.showMessageDialog;
import javax.swing.WindowConstants;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.text.JTextComponent;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Angel
 */
public class AgregarProductos extends javax.swing.JPanel {

    private Producto producto;

    /**
     * Creates new form AgregarProductos
     */
    public AgregarProductos() {
        initComponents();
        producto = new Producto();
        setVisibleTalla(false);
    }

    private void setVisibleTalla(boolean b) {
        JComponent componentesTalla[] = {tfTalla, lblTalla};
        for (JComponent c : componentesTalla) {
            c.setVisible(b);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabel1 = new javax.swing.JLabel();
        tfNombre = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jImageBox1 = new JImageBox();
        jLabel2 = new javax.swing.JLabel();
        lblTalla = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tfColor = new javax.swing.JTextField();
        tfFotoRuta = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        tfPrecio = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        cmbTipo = new javax.swing.JComboBox<>();
        tfTalla = new javax.swing.JTextField();

        setBackground(new java.awt.Color(0, 102, 102));
        setForeground(new java.awt.Color(153, 255, 255));
        setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(getFont());
        jLabel1.setForeground(getForeground());
        jLabel1.setText("Nombre");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        add(jLabel1, gridBagConstraints);

        tfNombre.setBackground(null);
        tfNombre.setFont(getFont());
        tfNombre.setForeground(getForeground());
        tfNombre.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        tfNombre.setCaretColor(getForeground());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        add(tfNombre, gridBagConstraints);

        jScrollPane1.setBackground(new java.awt.Color(102, 102, 102));
        jScrollPane1.setBorder(null);
        jScrollPane1.setMinimumSize(new java.awt.Dimension(1, 1));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(1, 1));

        jTextArea1.setColumns(20);
        jTextArea1.setFont(getFont());
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setBorder(null);
        jTextArea1.setOpaque(false);
        jScrollPane1.setViewportView(jTextArea1);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 60;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        add(jScrollPane1, gridBagConstraints);

        jImageBox1.setForeground(new java.awt.Color(255, 255, 255));
        jImageBox1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/IconoImagen.png"))); // NOI18N
        jImageBox1.setText("Cargar Imagen");
        jImageBox1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jImageBox1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jImageBox1.setPreferredSize(new java.awt.Dimension(100, 100));
        jImageBox1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jImageBox1MouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 20, 20);
        add(jImageBox1, gridBagConstraints);

        jLabel2.setFont(getFont());
        jLabel2.setForeground(getForeground());
        jLabel2.setText("Color");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        add(jLabel2, gridBagConstraints);

        lblTalla.setFont(getFont());
        lblTalla.setForeground(getForeground());
        lblTalla.setText("Talla");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        add(lblTalla, gridBagConstraints);

        jLabel4.setFont(getFont());
        jLabel4.setForeground(getForeground());
        jLabel4.setText("Descripción");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(0, 20, 0, 0);
        add(jLabel4, gridBagConstraints);

        jLabel5.setFont(getFont());
        jLabel5.setForeground(getForeground());
        jLabel5.setText("Precio");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        add(jLabel5, gridBagConstraints);

        jLabel6.setFont(getFont());
        jLabel6.setForeground(getForeground());
        jLabel6.setText("Foto");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        add(jLabel6, gridBagConstraints);

        tfColor.setBackground(null);
        tfColor.setFont(getFont());
        tfColor.setForeground(getForeground());
        tfColor.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        tfColor.setCaretColor(getForeground());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        add(tfColor, gridBagConstraints);

        tfFotoRuta.setEditable(false);
        tfFotoRuta.setBackground(null);
        tfFotoRuta.setFont(getFont());
        tfFotoRuta.setForeground(getForeground());
        tfFotoRuta.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        tfFotoRuta.setCaretColor(getForeground());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        add(tfFotoRuta, gridBagConstraints);

        jButton1.setBackground(new java.awt.Color(51, 51, 51));
        jButton1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Guardar");
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipady = 15;
        gridBagConstraints.weighty = 1.0;
        add(jButton1, gridBagConstraints);

        tfPrecio.setBackground(null);
        tfPrecio.setFont(getFont());
        tfPrecio.setForeground(getForeground());
        tfPrecio.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        tfPrecio.setCaretColor(getForeground());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        add(tfPrecio, gridBagConstraints);

        jLabel7.setFont(getFont());
        jLabel7.setForeground(getForeground());
        jLabel7.setText("Tipo");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        add(jLabel7, gridBagConstraints);

        cmbTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona", "Artículo Deportivo", "Vestimenta" }));
        cmbTipo.setSelectedIndex(1);
        cmbTipo.setBorder(null);
        cmbTipo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbTipoItemStateChanged(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        add(cmbTipo, gridBagConstraints);

        tfTalla.setBackground(null);
        tfTalla.setFont(getFont());
        tfTalla.setForeground(getForeground());
        tfTalla.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        tfTalla.setCaretColor(getForeground());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        add(tfTalla, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void jImageBox1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jImageBox1MouseClicked
        try {
            JFileChooser j = new JFileChooser();
            FileNameExtensionFilter fil = new FileNameExtensionFilter("JPG, PNG & GIF", "jpg", "png", "gif");
            j.setFileFilter(fil);
            String ruta = "";
            if (j.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
                ruta = j.getSelectedFile().getAbsolutePath();
                tfFotoRuta.setText(ruta);
            }
            File archivo = new File(ruta);
            producto.Foto = new byte[(int) archivo.length()];
            InputStream input = new FileInputStream(ruta);
            input.read(producto.Foto);
            BufferedImage image = null;
            InputStream in = new ByteArrayInputStream(producto.Foto);
            image = ImageIO.read(in);
            jImageBox1.setIcon(new ImageIcon(image));
            jImageBox1.setText("");
        } catch (HeadlessException | IOException ex) {
            System.out.println(ex);
        }
    }//GEN-LAST:event_jImageBox1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            conectar();
            llenarProducto();
            String sql = (cmbTipo.getSelectedIndex()==2)? "call InsertarPrendas(?,?,?,?,?,?,?);":"INSERT INTO Producto (idProducto, nombre, color, precio, tipo, descripción, Foto) VALUES (NULL,?,?,?,?,?,?);";
            PreparedStatement ps;
            ps = cnn.prepareStatement(sql);
            ps.setString(1, producto.nombre);
            ps.setString(2, producto.color);
            ps.setFloat(3, producto.precio);
            ps.setString(4, producto.tipo);
            ps.setString(5, producto.descripcion);
            ps.setBytes(6, producto.Foto);
            if (cmbTipo.getSelectedIndex()==2)
                ps.setString(7, producto.talla);
            System.out.println(ps);
            ps.execute();
            showMessageDialog(this, "Almacenado Correctamente");
            System.exit(0);
        } catch (SQLException ex) {
            System.out.println(ex);
        } catch (Exception ex) {
            System.out.println(ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void llenarProducto(){
        try {
            int cmb = cmbTipo.getSelectedIndex();
            if (cmb == 0) {
                throw new Exception("Rellena los campos");
            }
            JTextComponent[] textos = (cmb == 1) ? new JTextComponent[] {tfNombre, tfColor, tfPrecio, jTextArea1} :
                    new JTextComponent[] {tfNombre, tfColor, tfPrecio, jTextArea1, tfTalla} ;
            for (JTextComponent c : textos) {
                if (c.getText().equals("")) {
                    throw new Exception("Rellena los campos");
                }
            }
            int i = 0;
            producto.tipo = cmbTipo.getSelectedItem().toString();
            producto.nombre = textos[i++].getText();
            producto.color = textos[i++].getText();
            producto.precio = Float.parseFloat(textos[i++].getText());
            producto.descripcion = textos[i++].getText();
            if (cmb == 2)
                producto.talla = textos[i++].getText();
        } catch (NumberFormatException ex){
            showMessageDialog(this, "Por favor, escribe el precio correctamente");
        } catch (Exception ex) {
            showMessageDialog(this, ex.getMessage());
        }
    }

    private void cmbTipoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbTipoItemStateChanged
        setVisibleTalla(cmbTipo.getSelectedIndex() == 2);
    }//GEN-LAST:event_cmbTipoItemStateChanged

    public static void main(){
        JFrame x = new JFrame();
        AgregarProductos d = new AgregarProductos();
        x.add(d);
        x.setSize(800, 400);
        x.setVisible(true);
        x.setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
    }
    
    public static void main(String[] args) {
        main();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbTipo;
    private javax.swing.JButton jButton1;
    private JImageBox jImageBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lblTalla;
    private javax.swing.JTextField tfColor;
    private javax.swing.JTextField tfFotoRuta;
    private javax.swing.JTextField tfNombre;
    private javax.swing.JTextField tfPrecio;
    private javax.swing.JTextField tfTalla;
    // End of variables declaration//GEN-END:variables
}
