
import javax.swing.JFrame;
import javax.swing.WindowConstants;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Angel
 */
public class PnlCarrito extends javax.swing.JPanel {

    /**
     * Creates new form TerminarPedido
     */
    public PnlCarrito() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jImageBox2 = new JImageBox();
        jButton1 = new javax.swing.JButton();
        jImageBox1 = new JImageBox();

        setBackground(new java.awt.Color(51, 51, 51));
        setLayout(new java.awt.GridBagLayout());

        jImageBox2.setBackground(new java.awt.Color(255, 255, 255));
        jImageBox2.setForeground(new java.awt.Color(255, 255, 255));
        jImageBox2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jImageBox2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Carrito-Blanco.png"))); // NOI18N
        jImageBox2.setText(" Carrito");
        jImageBox2.setFont(new java.awt.Font("Unispace", 0, 36)); // NOI18N
        jImageBox2.setMaximumSize(new java.awt.Dimension(2000, 2000));
        jImageBox2.setMinimumSize(new java.awt.Dimension(700, 60));
        jImageBox2.setPreferredSize(new java.awt.Dimension(700, 60));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(15, 15, 15, 15);
        add(jImageBox2, gridBagConstraints);

        jButton1.setText("Agregar Productos");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        add(jButton1, gridBagConstraints);

        jImageBox1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/WallpaperCarrito.jpg"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.gridheight = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        add(jImageBox1, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        AgregarProductos.main();
    }//GEN-LAST:event_jButton1ActionPerformed

    public static void main(){
        JFrame x = new JFrame();
        x.add(new PnlCarrito());
        x.setSize(532, 358);
        x.setVisible(true);
        x.setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
    }
    
    public static void main(String[] args) {
        main();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private JImageBox jImageBox1;
    private JImageBox jImageBox2;
    // End of variables declaration//GEN-END:variables
}
