
import static Conexion.Conexion.*;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import static javax.swing.JOptionPane.showMessageDialog;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author PC
 */
public class ventanaLogin extends javax.swing.JFrame {

    /**
     * Creates new form ventanaLogin
     */
    public ventanaLogin() {
        initComponents();
        conectar();
        pnlIniciar.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlIniciar = new LIB.JPanelRound();
        txtUsuarioI = new LIB.FSTexFieldMD();
        txtPassI = new LIB.FSPasswordFieldMD();
        chxTer1 = new javax.swing.JCheckBox();
        lblReg = new javax.swing.JLabel();
        jPanelRound3 = new LIB.JPanelRound();
        lblIniciarS = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        pnlReg = new LIB.JPanelTransparente();
        txtNombre = new LIB.FSTexFieldMD();
        txtUsuario = new LIB.FSTexFieldMD();
        txtPass = new LIB.FSPasswordFieldMD();
        txtTel = new LIB.FSTexFieldMD();
        chxTer = new javax.swing.JCheckBox();
        lblIniciar = new javax.swing.JLabel();
        jPanelRound2 = new LIB.JPanelRound();
        lblRegistro = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlIniciar.setColorPrimario(new java.awt.Color(0, 0, 0));
        pnlIniciar.setColorSecundario(new java.awt.Color(23, 93, 96));
        pnlIniciar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtUsuarioI.setForeground(new java.awt.Color(255, 255, 255));
        txtUsuarioI.setBordeColorFocus(new java.awt.Color(210, 192, 48));
        txtUsuarioI.setColorTransparente(true);
        txtUsuarioI.setFont(new java.awt.Font("Roboto Bold", 1, 15)); // NOI18N
        txtUsuarioI.setPlaceholder("Usuario");
        pnlIniciar.add(txtUsuarioI, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 310, -1));

        txtPassI.setBackground(new java.awt.Color(204, 204, 204));
        txtPassI.setForeground(new java.awt.Color(51, 51, 51));
        txtPassI.setBordeColorFocus(new java.awt.Color(210, 192, 48));
        txtPassI.setFont(new java.awt.Font("Roboto Bold", 1, 15)); // NOI18N
        txtPassI.setOpaque(false);
        txtPassI.setPlaceholder("Contraseña");
        pnlIniciar.add(txtPassI, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 310, -1));

        chxTer1.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        chxTer1.setForeground(new java.awt.Color(255, 255, 255));
        chxTer1.setText("Mantener sesión iniciada");
        chxTer1.setOpaque(false);
        pnlIniciar.add(chxTer1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, 250, -1));

        lblReg.setBackground(new java.awt.Color(255, 255, 255));
        lblReg.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        lblReg.setForeground(new java.awt.Color(255, 255, 255));
        lblReg.setText("No tienes una cuenta? Registrate");
        lblReg.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblReg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblRegMouseClicked(evt);
            }
        });
        pnlIniciar.add(lblReg, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 340, -1, -1));

        jPanelRound3.setBackground(new java.awt.Color(194, 178, 44));
        jPanelRound3.setToolTipText("");
        jPanelRound3.setOpaque(true);

        lblIniciarS.setFont(new java.awt.Font("Segoe UI Semibold", 1, 21)); // NOI18N
        lblIniciarS.setForeground(new java.awt.Color(255, 255, 255));
        lblIniciarS.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIniciarS.setText("Iniciar Sesión");
        lblIniciarS.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblIniciarS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblIniciarSMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanelRound3Layout = new javax.swing.GroupLayout(jPanelRound3);
        jPanelRound3.setLayout(jPanelRound3Layout);
        jPanelRound3Layout.setHorizontalGroup(
            jPanelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRound3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblIniciarS, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelRound3Layout.setVerticalGroup(
            jPanelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelRound3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblIniciarS, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pnlIniciar.add(jPanelRound3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 160, -1));

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_facebook_42px_1.png"))); // NOI18N
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(127, 16, -1, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_twitter_42px_2.png"))); // NOI18N
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(187, 16, -1, -1));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_google_42px.png"))); // NOI18N
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(247, 16, -1, -1));

        pnlIniciar.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 518, 420, 80));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/pngegg (17) 1.png"))); // NOI18N
        pnlIniciar.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 300, 490));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Rectangle 1.png"))); // NOI18N
        pnlIniciar.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, -50, 180, 600));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Group 2.png"))); // NOI18N
        pnlIniciar.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, 600));

        pnlReg.setColorPrimario(new java.awt.Color(0, 0, 0));
        pnlReg.setColorSecundario(new java.awt.Color(23, 93, 96));
        pnlReg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtNombre.setForeground(new java.awt.Color(255, 255, 255));
        txtNombre.setBordeColorFocus(new java.awt.Color(248, 179, 13));
        txtNombre.setColorTransparente(true);
        txtNombre.setFont(new java.awt.Font("Roboto Bold", 1, 15)); // NOI18N
        txtNombre.setOpaque(false);
        txtNombre.setPlaceholder("Nombre");
        pnlReg.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 310, -1));

        txtUsuario.setForeground(new java.awt.Color(255, 255, 255));
        txtUsuario.setBordeColorFocus(new java.awt.Color(248, 179, 13));
        txtUsuario.setColorTransparente(true);
        txtUsuario.setFont(new java.awt.Font("Roboto Bold", 1, 15)); // NOI18N
        txtUsuario.setPlaceholder("Usuario");
        pnlReg.add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 310, -1));

        txtPass.setBackground(new java.awt.Color(204, 204, 204));
        txtPass.setForeground(new java.awt.Color(51, 51, 51));
        txtPass.setText("fSPasswordFieldMD2");
        txtPass.setBordeColorFocus(new java.awt.Color(248, 179, 13));
        txtPass.setFont(new java.awt.Font("Roboto Bold", 1, 15)); // NOI18N
        txtPass.setOpaque(false);
        txtPass.setPlaceholder("Contraseña");
        pnlReg.add(txtPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, 310, -1));

        txtTel.setForeground(new java.awt.Color(255, 255, 255));
        txtTel.setBordeColorFocus(new java.awt.Color(248, 179, 13));
        txtTel.setColorTransparente(true);
        txtTel.setFont(new java.awt.Font("Roboto Bold", 1, 15)); // NOI18N
        txtTel.setPlaceholder("Telefono");
        txtTel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtTelKeyPressed(evt);
            }
        });
        pnlReg.add(txtTel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, 310, -1));

        chxTer.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        chxTer.setForeground(new java.awt.Color(255, 255, 255));
        chxTer.setText("Aceptar Terminos y Condiciones");
        chxTer.setOpaque(false);
        pnlReg.add(chxTer, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 350, 250, -1));

        lblIniciar.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        lblIniciar.setForeground(new java.awt.Color(255, 255, 255));
        lblIniciar.setText("Tienes una cuenta? Inicia Sesión");
        lblIniciar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblIniciar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblIniciarMouseClicked(evt);
            }
        });
        pnlReg.add(lblIniciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 420, -1, -1));

        jPanelRound2.setBackground(new java.awt.Color(248, 179, 13));
        jPanelRound2.setToolTipText("");
        jPanelRound2.setOpaque(true);

        lblRegistro.setFont(new java.awt.Font("Segoe UI Semibold", 1, 21)); // NOI18N
        lblRegistro.setForeground(new java.awt.Color(255, 255, 255));
        lblRegistro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRegistro.setText("Registrarse");
        lblRegistro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblRegistro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblRegistroMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanelRound2Layout = new javax.swing.GroupLayout(jPanelRound2);
        jPanelRound2.setLayout(jPanelRound2Layout);
        jPanelRound2Layout.setHorizontalGroup(
            jPanelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelRound2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanelRound2Layout.setVerticalGroup(
            jPanelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelRound2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pnlReg.add(jPanelRound2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 410, -1, -1));

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_facebook_42px_1.png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_twitter_42px_2.png"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_google_42px.png"))); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 20, -1, -1));

        pnlReg.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 520, 420, 80));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/PngItem_14348 1.png"))); // NOI18N
        pnlReg.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, -10, 450, 610));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Rectangle 10.png"))); // NOI18N
        pnlReg.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, -50, 180, 600));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Group 2.png"))); // NOI18N
        pnlReg.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, 600));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlIniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 2, Short.MAX_VALUE)
                    .addComponent(pnlReg, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 3, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(pnlIniciar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(pnlReg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblRegistroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRegistroMouseClicked
        try {
            st = cnn.createStatement();
            String R[] = new String[4];
            R[0] = txtNombre.getText();
            R[1] = txtPass.getText();
            R[2] = txtPass.getText();
            R[3] = txtTel.getText();
            String sql = "INSERT INTO cliente (Nombre,Usuario,Contraseña,Telefono)VALUES ('" + R[0] + "','" + R[1] + "','" + R[2] + "','" + R[3] + "')"; //Consulta sql
            System.out.print(sql);
            st.executeUpdate(sql);
        } catch (SQLException ex) {
            Logger.getLogger(ventanaLogin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_lblRegistroMouseClicked

    private void txtTelKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelKeyPressed
        
    }//GEN-LAST:event_txtTelKeyPressed

    private void lblIniciarSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblIniciarSMouseClicked
        try {
            st = cnn.createStatement();
            String u = "";
            String p;
            String sql = "SELECT Usuario,Contraseña from cliente where Usuario='" + txtUsuarioI.getText() + "'";  //Consulta sql
            ResultSet resultado = st.executeQuery(sql);  //Linea que ejecuta la consulta sql y almacena los datos en resultado
            if (resultado.next()) {                                    //Bucle que recorre la consulta obtenida
                u = resultado.getString("usuario");
                p = resultado.getString("contraseña");
                
                //showMessageDialog(null,p);
                if (txtPassI.getText().equals(p)) {                   
                    System.out.println("Iniciaste sesión correctamente");
                    PnlCarrito.main();
                    this.dispose();
                    //Lo que pasa cuando inicias sesión correctamente
                } else {
                    showMessageDialog(null, "CONTRASEÑA INCORRECTA");
                }
            } else {
                showMessageDialog(null, "NO EXISTE EL USUARIO");
            }
        } catch (SQLException ex) {
            showMessageDialog(null, "Error al cargar los Datos\n" + ex);
        }
    }//GEN-LAST:event_lblIniciarSMouseClicked

    private void lblIniciarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblIniciarMouseClicked
        pnlReg.setVisible(false);
        pnlIniciar.setVisible(true);
    }//GEN-LAST:event_lblIniciarMouseClicked

    private void lblRegMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRegMouseClicked
        pnlReg.setVisible(true);
        pnlIniciar.setVisible(false);
    }//GEN-LAST:event_lblRegMouseClicked

    public void cargarDatos() {
        String datos[] = new String[4];    //Variable que almacena los datos de la consulta
        String sql = "select * from Usuarios";  //Consulta sql
        try {
            ResultSet resultado = st.executeQuery(sql);  //Linea que ejecuta la consulta sql y almacena los datos en resultado

            while (resultado.next()) {                                    //Bucle que recorre la consulta obtenida
                datos[0] = resultado.getInt("id_usuario") + "";
                datos[1] = resultado.getString("username");
                datos[2] = resultado.getString("password") + "";
                datos[3] = resultado.getString("privilegio") + "";
                //m.addRow(datos);
            }
        } catch (SQLException ex) {
            showMessageDialog(null, "Error al cargar los Datos\n" + ex);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ventanaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ventanaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ventanaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ventanaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ventanaLogin().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox chxTer;
    private javax.swing.JCheckBox chxTer1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private LIB.JPanelRound jPanelRound2;
    private LIB.JPanelRound jPanelRound3;
    private javax.swing.JLabel lblIniciar;
    private javax.swing.JLabel lblIniciarS;
    private javax.swing.JLabel lblReg;
    private javax.swing.JLabel lblRegistro;
    private LIB.JPanelRound pnlIniciar;
    private LIB.JPanelTransparente pnlReg;
    private LIB.FSTexFieldMD txtNombre;
    private LIB.FSPasswordFieldMD txtPass;
    private LIB.FSPasswordFieldMD txtPassI;
    private LIB.FSTexFieldMD txtTel;
    private LIB.FSTexFieldMD txtUsuario;
    private LIB.FSTexFieldMD txtUsuarioI;
    // End of variables declaration//GEN-END:variables
}
